            - name: ZAP API Scan
  # You may pin to the exact commit or the version.
  # uses: zaproxy/action-api-scan@411cbe8fc59d9966a77d61b50daf6c49b6763605
  uses: zaproxy/action-api-scan@v0.6.0
  with:
    # GitHub Token to create issues in the repository
    token: # optional, default is ${{ github.token }}
    # Target URL
    target: https://github.com/Lama22hh/semicolon.git
    # Format openapi, soap or graphql
    format: # optional, default is openapi
    # Relative path of the ZAP configuration file
    rules_file_name: # optional
    # The Docker file to be executed
    docker_name: # default is ghcr.io/zaproxy/zaproxy:stable
    # Additional command line options
    cmd_options: # optional
    # The title for the GitHub issue to be created
    issue_title: # optional, default is ZAP API Scan Report
    # The action status will be set to fail if ZAP identifies any alerts during the api scan
    fail_action: # optional
    # The action will file the report to the GitHub issue using the issue_title input
    allow_issue_writing: # optional, default is true
    # The name of the artifact that contains the ZAP reports
    artifact_name: # optional, default is zap_scan
          
